### ISSUE TITLE
Error while installing flipCluster / flipAnalysisOfVariance

### ISSUE THREAD

**Issue by manuelwaltschek** [Displayr/flipAnalysisOfVariance#1]
Hello there, I tried to install package flipCluster in RStudio with 
`install_github("Displayr/flipCluster")` which led to an error because of the dependency to flipAnalysisOfVariance package.

When I tried to install flipAnalysisOfVariance, another error occured:

> installing *source* package 'flipAnalysisOfVariance' ...
> ** R
> ** tests
> ** preparing package for lazy loading
> Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
>   there is no package called 'TH.data'
> ERROR: lazy loading failed for package 'flipAnalysisOfVariance'
> removing 'C:/Users/manuel.waltschek/Documents/R/win-library/3.4/flipAnalysisOfVariance'
> In R CMD INSTALL
> Installation failed: Command failed (1)

**Comment by mwmclean** [comment]
What happens if you try `install.packages("TH.data")`?

**Comment by manuelwaltschek** [comment]
Thanks for the reply, it worked as you suggested.
